source "vmware-iso" "autogenerated_3" {
  boot_command        = ["<enter><wait><f6><esc><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>", "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>", "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>", "<bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs>", "/install/vmlinuz<wait>", " auto<wait>", " console-setup/ask_detect=false<wait>", " console-setup/layoutcode=us<wait>", " console-setup/modelcode=pc105<wait>", " debconf/frontend=noninteractive<wait>", " debian-installer=en_US<wait>", " fb=false<wait>", " initrd=/install/initrd.gz<wait>", " kbd-chooser/method=us<wait>", " keyboard-configuration/layout=USA<wait>", " keyboard-configuration/variant=USA<wait>", " locale=en_US<wait>", " netcfg/get_domain=vm<wait>", " netcfg/get_hostname=${var.vmname}<wait>", " grub-installer/bootdev=/dev/sda<wait>", " noapic<wait>", " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg", " -- <wait>", "<enter><wait>"]
  boot_wait           = "10s"
  disk_size           = "30720"
  format              = "ova"
  guest_os_type       = "ubuntu-64"
  headless            = true
  http_directory      = "http"
  iso_checksum        = "${var.checksum}"
  iso_checksum_type   = "${var.checksumtype}"
  iso_urls            = "${var.iso_ubuntu}"
  keep_registered     = true
  output_directory    = "vm-${var.vmname}"
  shutdown_command    = "echo 'vagrant'|sudo -S shutdown -P now"
  ssh_password        = "vagrant"
  ssh_port            = 22
  ssh_username        = "vagrant"
  ssh_wait_timeout    = "100000s"
  tools_upload_flavor = "linux"
  vm_name             = "${var.vmname}"
  vmdk_name           = "${var.vmname}"
  vmx_data = {
    "cpuid.coresPerSocket" = "1"
    memsize                = "3072"
    numvcpus               = "2"
  }
}