source "vmware-vmx" "autogenerated_4" {
  boot_wait           = "90s"
  format              = "ova"
  headless            = false
  shutdown_command    = "echo '/sbin/shutdown -h -P now' > /tmp/shutdown.sh; echo 'vagrant'|sudo -S sh '/tmp/shutdown.sh'"
  shutdown_timeout    = "90m"
  source_path         = "output-vmware-iso/${var.vmname}.vmx"
  ssh_password        = "vagrant"
  ssh_username        = "vagrant"
  tools_upload_flavor = "linux"
  vm_name             = "${var.vmname}"
}